require_https = true
include_fragments = true
remap = [
  # TODO: remove when this is fixed https://github.com/lycheeverse/lychee/issues/1729
  "https://github.com/(.*?)/(.*?)/blob/(.*?)/(.*#.*)$ https://raw.githubusercontent.com/$1/$2/$3/$4"
]
exclude = [
  # TODO: remove when this is fixed https://github.com/pradyunsg/furo/issues/907
  '^http://github\.com/cferdinandi/gumshoe$',
]
