name: 🙌 Feature Request
description: Suggest a new feature or change to msgspec
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out a feature request!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the feature. What problems does it solve?

        If the feature is to related to a problem, please describe in detail
        your use case. What would this new feature help you do that you
        couldn't do before? Why is this useful?

        When relevant, please also include example code making use of your
        proposed feature. How would you use this feature? What would code using
        it look like?
    validations:
      required: true
