class Struct:
    def __init__(self, *args, **kwargs) -> None: ...
    def __init_subclass__(cls, asarray: bool = False, frozen: bool = False) -> None: ...

class MsgspecError(Exception): ...
class DecodingError(MsgspecError): ...
class EncodingError(MsgspecError): ...

from . import msgpack
from . import json

__version__ : str
